In [1]:
!pip install numpy

In [3]:
import numpy as np

# 1.- Generamos una matriz cuadrada de 4x4
A = np.random.rand(4, 4)
print("Matriz A (4x4):")
print(A)

# 2.- Calculamos la inversa
A_inv = np.linalg.inv(A)
print("\nInversa de A:")
print(A_inv)

# 3.- Calculamos la traspuesta
A_t = A.T
print("\nTraspuesta de A:")
print(A_t)

# 4.- Multiplicamos la matriz por un escalar
escalar = 5
A_escalar = A * escalar
print("\nMatriz A multiplicada por el escalar", escalar, ":")
print(A_escalar)

# 5.- Realizamos el producto interno con una nueva matriz de dimensiones 4x2
B = np.random.rand(4, 2)
print("\nMatriz B (4x2):")
print(B)

producto_interno = np.dot(A, B)
print("\nProducto interno de A y B:")
print(producto_interno)


Matriz A (4x4):
[[0.185928   0.2963447  0.36027766 0.80631419]
 [0.91212012 0.22972453 0.19849329 0.99892463]
 [0.53541144 0.56456116 0.28858571 0.89396689]
 [0.57992952 0.43393303 0.56157461 0.72820741]]

Inversa de A:
[[-1.90572399  0.95021651 -0.11221291  0.94441811]
 [-1.70853271 -1.58135965  3.37094578 -0.07723163]
 [ 0.70352689 -0.54415961 -2.17758407  2.6407295 ]
 [ 1.99323918  0.60522839 -0.24005962 -1.36932036]]

Traspuesta de A:
[[0.185928   0.91212012 0.53541144 0.57992952]
 [0.2963447  0.22972453 0.56456116 0.43393303]
 [0.36027766 0.19849329 0.28858571 0.56157461]
 [0.80631419 0.99892463 0.89396689 0.72820741]]

Matriz A multiplicada por el escalar 5 :
[[0.92964002 1.48172348 1.80138832 4.03157097]
 [4.56060059 1.14862266 0.99246644 4.99462315]
 [2.6770572  2.82280581 1.44292854 4.46983447]
 [2.89964761 2.16966513 2.80787306 3.64103704]]

Matriz B (4x2):
[[0.4017116  0.69932016]
 [0.00378027 0.76492795]
 [0.05882575 0.23627008]
 [0.12438819 0.1084964 ]]

Producto interno d